package cmodule.AwayPhysics;

@:final extern class FSM__ZN16btRaycastVehicle20updateWheelTransformEib extends Machine {
	var f0 : Float;
	var f1 : Float;
	var f10 : Float;
	var f11 : Float;
	var f12 : Float;
	var f13 : Float;
	var f14 : Float;
	var f15 : Float;
	var f16 : Float;
	var f17 : Float;
	var f18 : Float;
	var f19 : Float;
	var f2 : Float;
	var f20 : Float;
	var f21 : Float;
	var f22 : Float;
	var f23 : Float;
	var f24 : Float;
	var f25 : Float;
	var f26 : Float;
	var f27 : Float;
	var f28 : Float;
	var f29 : Float;
	var f3 : Float;
	var f30 : Float;
	var f31 : Float;
	var f4 : Float;
	var f5 : Float;
	var f6 : Float;
	var f7 : Float;
	var f8 : Float;
	var f9 : Float;
	var i0 : Int;
	var i1 : Int;
	var i2 : Int;
	var i3 : Int;
	function new() : Void;
	static var NumberRegCount(default,never) : Int;
	static var intRegCount(default,never) : Int;
	static function start() : Void;
}
