package away3d.core.base;

extern class SubGeometryBase {
	var UVData(default,never) : flash.Vector<Float>;
	var UVOffset(default,never) : Int;
	var UVStride(default,never) : UInt;
	var autoDeriveVertexNormals : Bool;
	var autoDeriveVertexTangents : Bool;
	var autoGenerateDummyUVs : Bool;
	var faceNormals(default,never) : flash.Vector<Float>;
	var indexData(default,never) : flash.Vector<UInt>;
	var numTriangles(default,never) : UInt;
	var parentGeometry : Geometry;
	var scaleU(default,never) : Float;
	var scaleV(default,never) : Float;
	var useFaceWeights : Bool;
	var vertexData(default,never) : flash.Vector<Float>;
	var vertexNormalData(default,never) : flash.Vector<Float>;
	var vertexNormalOffset(default,never) : Int;
	var vertexNormalStride(default,never) : UInt;
	var vertexOffset(default,never) : Int;
	var vertexPositionData(default,never) : flash.Vector<Float>;
	var vertexStride(default,never) : UInt;
	var vertexTangentData(default,never) : flash.Vector<Float>;
	var vertexTangentOffset(default,never) : Int;
	var vertexTangentStride(default,never) : UInt;
	function new() : Void;
	function applyTransformation(p1 : flash.geom.Matrix3D) : Void;
	function dispose() : Void;
	function getIndexBuffer(p1 : away3d.core.managers.Stage3DProxy) : flash.display3D.IndexBuffer3D;
	function scale(p1 : Float) : Void;
	function scaleUV(p1 : Float = 1, p2 : Float = 1) : Void;
	function updateIndexData(p1 : flash.Vector<UInt>) : Void;
}
